### ISSUE TITLE
Detalle de artículo: almacen no visible

### ISSUE THREAD

**Issue by Kyostenas** [RafaelAngelRamirez/control-de-produccion-API#10]
Al ver el detalle del artículo, el campo de almacen está vacío a pesar de que el artículo tiene dicho campo lleno.
![image](https://user-images.githubusercontent.com/57164866/84051092-3f359c80-a974-11ea-93c3-44e10d960360.png)
![image](https://user-images.githubusercontent.com/57164866/84051132-4d83b880-a974-11ea-96b8-c21a4e94dedf.png)

**Comment by RafaelAngelRamirez** [comment]
Transferido por que el problema solo se encuentra en la API y no en el GUI como se pensaba

**Comment by Kyostenas** [comment]
Terminado. Este es el [pull  request](https://github.com/RafaelAngelRamirez/control-de-produccion-API/pull/9)
