### ISSUE TITLE
S00002 - Mejoras de rendimiento en folio

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [RafaelAngelRamirez/control-de-produccion-API#67]
- [x] Mejora de soporte para folios de gran tamaño. (Modificar tamaño de payload. Son 2 lugares en app.js a 150MB)
![image](https://user-images.githubusercontent.com/27775245/156413880-a762826d-4fbc-4630-b85d-03ad296d7a85.png)

      - Descargar base de datos desde producción.
- [x] Que corra correctamente en PM2. 
- [x] Implementación de nueva versión en servidor.

**Comment by Kyostenas** [comment]
Trabajando en ello

**Comment by Kyostenas** [comment]
Error encontrado:
```FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory```

**Comment by Kyostenas** [comment]
Se replicó el error con una serie de pedidos en un nuevo folio. Se comprobó que se pudieran generar las ordenes (lineas).

![image](https://user-images.githubusercontent.com/57164866/157191580-7b92c352-5392-4e34-b3e8-b6d7e68da107.png)

Se modificó ```app.js``` para que permita payloads de 150 mb.
